Update `How to use Kytos with Mininet` tutorial
kytos/documentation pull request #105
Opened 2021-01-18 16:37 UTC by cmagnobarbosa

# Pull Request Template

### :octocat: Are you working on some issue? Identify the issue!

Related https://github.com/kytos/kytos/issues/1225
### :bookmark_tabs: Description of the Change

Update tutorial to works properly after necessary changes by consistency mechanism.

### :page_facing_up: Release Notes

- Update `How to use Kytos with Mininet` tutorial

2021-01-19 18:32 UTC, josemauro requested changes

2021-01-19 18:32 UTC, josemauro commented on tutorials/napps/how_to_use_kytos_with_mininet.rst
> +to receive packets. You can do this using a REST client like `postman` or
Just a little suggestion:`Postman`

2021-01-19 22:29 UTC, cmagnobarbosa commented on tutorials/napps/how_to_use_kytos_with_mininet.rst
> +to receive packets. You can do this using a REST client like `postman` or
Resolved

2021-01-21 03:08 UTC, josemauro approved these changes

2021-01-21 03:08 UTC, josemauro commented on tutorials/napps/how_to_use_kytos_with_mininet.rst
> + $ kytos napps install kytos/flow_manager kytos/of_l2ls kytos/of_lldp
Did you split the installation command to get a better visualization (instead of keep one "kytos napps install" line)?

2021-01-21 03:08 UTC, josemauro commented on tutorials/napps/how_to_use_kytos_with_mininet.rst
> +To complete this, use the command below:
Why replace "do" by "complete"?

2021-01-21 12:32 UTC, cmagnobarbosa commented on tutorials/napps/how_to_use_kytos_with_mininet.rst
> + $ kytos napps install kytos/flow_manager kytos/of_l2ls kytos/of_lldp
Yes, the line was split to improve visualization.

2021-01-21 12:34 UTC, cmagnobarbosa commented on tutorials/napps/how_to_use_kytos_with_mininet.rst
> +To complete this, use the command below:
Nothing special I just followed LanguageTool recommendation

2021-01-25 16:54 UTC, hdiogenes commented on tutorials/napps/how_to_use_kytos_with_mininet.rst
> + $ kytos napps install kytos/flow_manager kytos/of_l2ls kytos/of_lldp
It's better to use the backslash at the end of the line for continuation @cmagnobarbosa.

2021-01-28 14:19 UTC, cmagnobarbosa commented on tutorials/napps/how_to_use_kytos_with_mininet.rst
> + $ kytos napps install kytos/flow_manager kytos/of_l2ls kytos/of_lldp
Resolved on commit https://github.com/kytos/documentation/pull/105/commits/75f152a1b215d5014e37b87071786aaac1709d27

2021-01-28 17:32 UTC, josemauro commented on tutorials/napps/how_to_use_kytos_with_mininet.rst
> +To complete this, use the command below:
Ok

2021-02-03 19:16 UTC, merged