Adding build docs
kytos/documentation pull request #48
Opened 2017-06-05 19:25 UTC by macartur

2017-06-06 17:11 UTC, diraol requested changes

2017-06-06 17:11 UTC, diraol commented on build_dirs/build_docs.py
> +BASE = os.path.abspath(os.path.dirname(__file__))
@macartur let's try to prioritize the use of PathLike objects for dealing with paths/dirs/files.

Can you please rewrite this PR considering this issue? Thanks! =)

2017-06-06 18:10 UTC, macartur commented on build_dirs/build_docs.py
> +BASE = os.path.abspath(os.path.dirname(__file__))
Done.

2017-06-06 18:13 UTC, diraol commented on build_dirs/build_docs.py
> +BASE = Path(os.path.abspath(os.path.dirname(__file__)))
Just check before changing, but I think that
`Path(os.path.abspath(os.path.dirname(__file__)))` == `Path(__file__).parent`

2017-06-06 18:59 UTC, diraol submitted a review, later dismissed

2017-06-08 13:17 UTC, beraldoleal commented
@macartur @diraol Hi guys... there is no automatic way to do that ? Like a integration already builtin on sphinx ?

2017-06-08 13:26 UTC, diraol commented
@macartur have you looked at this sphinx extensions?
https://robpol86.github.io/sphinxcontrib-versioning

2017-06-08 13:49 UTC, beraldoleal commented
@diraol good.. maybe there is others..

2017-06-09 20:18 UTC, macartur commented
So, I saw this sphinx extension, but the script `build_docs.py` is creating a folder with the structure below for all projects with the folder docs.

The structure of docs folder will be:
- docs
   - bethania
       - kytos
       - python-openflow
   - chico
        - kytos
        - python-openflow

And this is made locally using the tarballs stored in each release tag.
I will read more to find others sphinx extensions and a better way to do this.

2017-06-12 14:41 UTC, macartur commented
I found a nice package to build the docs: https://buildthedocs.pietroalbini.org/1.0/quickstart/

2017-06-12 17:20 UTC, beraldoleal commented
@macartur @diraol so, what is the status of this ?

2017-06-12 17:22 UTC, macartur commented
I am trying to do this issue using the buildthedocs package, but I had a problem with templates and styles.

2017-06-13 20:25 UTC, macartur commented
I will close this PR, each project will manage your sphinx version using sphinxcontrib-versioning.

2017-06-13 20:25 UTC, closed without merging